#version: '3.7'
services:
  db:
    container_name: dairy-db
    image: postgres:14.1
    restart: always
    networks:
      internal:
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: school
    ports:
      - "5432:5432"

networks:
  internal:
    name: "internal"
    external: false