@startuml
actor "Пользователь" as User
participant "Система" as System

User -> System : Заходит в личный кабинет
System -> User : Пользователь успешно авторизован
User -> System : Запрашивает просмотр\nи редактирование данных
System --> User : Отображает данные с\nвозможностью редактирования
User -> System : Изменяет данные и сохраняет изменения
System --> User : Сохраняет изменения и отображает\nсообщение об успешном обновлении
alt Система не может получить или сохранить данные
    System --> User : Отображает сообщение об ошибке
end
@enduml