@startuml
actor "Пользователь" as User
participant "Система" as System

User -> System : Заходит на поисковую страницу\nи запрашивает информацию об ученике
System -> System: Поиск информации об ученике
System --> User : Отображает информацию об ученике
alt Система не находит ученика
    System --> User : Отображает сообщение об отсутствии ученика
end
@enduml