@startuml
actor "Пользователь" as User
participant "Система" as System

User -> System : Заходит в личный кабинет
System -> User : Пользователь успешно авторизован
User -> System : Запрашивает просмотр информации\nи статистики
System --> User : Отображает данные о ученике
alt Система не может получить данные
    System --> User : Отображает сообщение об ошибке
end
@enduml